// Generated by CoffeeScript 1.3.1
(function() {

  describe("Router", function() {
    return describe("dispatcher", function() {
      return it("accepts a path, finds a controller and calls appropriate action", function() {
        return Agility.Router.dispatch("/home");
      });
    });
  });

}).call(this);
