// Generated by CoffeeScript 1.3.1
(function() {
  var __slice = [].slice;

  this.Agility = {};

  this.App = {
    Controllers: {}
  };

  Agility.Application = (function() {

    Application.name = 'Application';

    Application.prototype.routes = {};

    function Application() {
      this.router = new Agility.Router();
    }

    Application.prototype.populatesRoutes = function() {
      var method, path, _ref, _results;
      _ref = this.routes;
      _results = [];
      for (path in _ref) {
        method = _ref[path];
        _results.push(this.router.route(path, method));
      }
      return _results;
    };

    Application.prototype.run = function() {
      this.populatesRoutes();
      return this.init();
    };

    Application.prototype.init = function() {
      return Backbone.history.start();
    };

    return Application;

  })();

  Agility.Controller = (function() {

    Controller.name = 'Controller';

    function Controller() {}

    return Controller;

  })();

  Agility.Router = (function() {

    Router.name = 'Router';

    function Router() {
      this.router = new Backbone.Router;
    }

    Router.prototype.route = function(path, action) {
      var _this = this;
      return this.router.route(path, action, function() {
        var params;
        params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return _this.dispatch(action, params);
      });
    };

    Router.prototype.dispatch = function(action, params) {
      var controller, instance, method, _ref;
      _ref = action.split("#"), controller = _ref[0], method = _ref[1];
      instance = new App.Controllers[controller];
      return instance[method].apply(instance, params);
    };

    return Router;

  })();

}).call(this);
