// Generated by CoffeeScript 1.3.1
(function() {
  var ExampleApp,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  App.Controllers.Home = (function(_super) {

    __extends(Home, _super);

    Home.name = 'Home';

    function Home() {
      return Home.__super__.constructor.apply(this, arguments);
    }

    Home.prototype.welcome = function(name) {
      return alert(name);
    };

    return Home;

  })(Agility.Controller);

  ExampleApp = (function(_super) {

    __extends(ExampleApp, _super);

    ExampleApp.name = 'ExampleApp';

    function ExampleApp() {
      return ExampleApp.__super__.constructor.apply(this, arguments);
    }

    ExampleApp.prototype.root = '#root';

    ExampleApp.prototype.routes = {
      "": "Home#welcome",
      ":name": "Home#welcome"
    };

    return ExampleApp;

  })(Agility.Application);

  $(function() {
    App.instance = new ExampleApp();
    return App.instance.run();
  });

}).call(this);
